import type { Metadata } from "next";
import "./globals.css";
import { Geist_Mono } from "next/font/google";
import { Header } from "@/components/shared/header/Header";
import { TwitterScriptLoader } from "@/components/shared/twitter-embed";
import { Toaster } from "@/components/ui/sonner";

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`antialiased ${geistMono.className}`}>
				<Header />
				<main className="min-h-screen w-full pt-[72px]">{children}</main>
				<TwitterScriptLoader />
				<Toaster />
			</body>
		</html>
	);
}
